// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXP2IVBYfXNMPhQrGyFaYg7MzaB8SUvao',
    appId: '1:318423438284:web:3f1bcc5f03b8a7e64b8369',
    messagingSenderId: '318423438284',
    projectId: 'tspch-c13d2',
    authDomain: 'tspch-c13d2.firebaseapp.com',
    storageBucket: 'tspch-c13d2.firebasestorage.app',
    measurementId: 'G-V81GREKC8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTlZLj0Z81ThMyMXbOQOxLuoljcWHDdk',
    appId: '1:318423438284:android:cc82ee9606c5c76f4b8369',
    messagingSenderId: '318423438284',
    projectId: 'tspch-c13d2',
    storageBucket: 'tspch-c13d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANHuNWgqFh2RNqpcXKVy9nG78RGnwV-Xk',
    appId: '1:318423438284:ios:34b13ad7a9615bcd4b8369',
    messagingSenderId: '318423438284',
    projectId: 'tspch-c13d2',
    storageBucket: 'tspch-c13d2.firebasestorage.app',
    iosBundleId: 'com.example.tspch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANHuNWgqFh2RNqpcXKVy9nG78RGnwV-Xk',
    appId: '1:318423438284:ios:34b13ad7a9615bcd4b8369',
    messagingSenderId: '318423438284',
    projectId: 'tspch-c13d2',
    storageBucket: 'tspch-c13d2.firebasestorage.app',
    iosBundleId: 'com.example.tspch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXP2IVBYfXNMPhQrGyFaYg7MzaB8SUvao',
    appId: '1:318423438284:web:4467fc9eea610b894b8369',
    messagingSenderId: '318423438284',
    projectId: 'tspch-c13d2',
    authDomain: 'tspch-c13d2.firebaseapp.com',
    storageBucket: 'tspch-c13d2.firebasestorage.app',
    measurementId: 'G-08MNS2HBM7',
  );

}